### ISSUE TITLE
Is PyCifRW==4.4 required?

### ISSUE THREAD

**Issue by dr-geeno** [torbjornbjorkman/cif2cell#31]
Tried installing cif2cell using python3.8 on MacOS, but failed because it cannot install that specific version of PyCifRW, I got:

`error: legacy-install-failure`

I solved it by ignoring dependencies and then installing the most recent version of PyCifRW available, which is 4.4.3 on my system, and can run it. Is there a reason to use specifically 4.4 or other versions are also ok? In that case, I think it would be better to add them in the requirements/setup.

**Comment by ltalirz** [comment]
Hi @dr-geeno , thanks for reporting!

I believe I took this requirement from an earlier `requirements.txt` (or similar) in order not to introduce any changes.

Since your contribution involves CIF files, perhaps you could test a bit with a later PyCifRW version. If things seem to work fine, feel free to open a PR that replaces `==` with `>=`.

**Comment by dr-geeno** [comment]
Thanks for the answer @ltalirz !

I see. As I said, I have installed 4.4.3, so will report in case something goes wrong. Looking quickly through the [commits of the package](https://bitbucket.org/jamesrhester/pycifrw/commits/) seems mostly bug fixes, so I think it would be fine.

If I find some time and find a machine where I can install 4.4, I will test for any difference.

**Comment by ltalirz** [comment]
Ah ok, in that case, simply replace it with `~=4.4` that should be fine (sorry, didn't realize this was just about 4.4.x)

You can do this as part of your PR

**Comment by dr-geeno** [comment]
Ok, I will change it! #30
