### ISSUE TITLE
Installation from pip is not up-to-date

### ISSUE THREAD

**Issue by dr-geeno** [torbjornbjorkman/cif2cell#36]
I made a contribution last year adding the option for the crymol program of GNXAS. Recently did a school regarding the code and the participants had to install the program from sources because the repository on pip is not up-to-date. Can it be updated?

**Comment by ltalirz** [comment]
Hi @dr-geeno, I saw your offer to help in https://github.com/torbjornbjorkman/cif2cell/issues/35#issuecomment-1718500504 - thanks for that!

The steps I would suggest here:
- create a pull request to update the version to 2.1.0 in two places
```
$ git grep "2\.0\.0"
binaries/cif2cell:version = "2.0.0"
setup.py:      version='2.0.0a5',
``` 
- create a pypi account and let me know. I will add you to the contributors of the cif2cell pypi project
- (optional) prepare a github action workflow that will automatically push to Pypi (using [this](https://github.com/marketplace/actions/pypi-publish)) when we add a tag to the repository

then we'll together make a 2.1.0 release that includes your features

**Comment by dr-geeno** [comment]
Hi @ltalirz , thanks for your answer and sorry for the delay.

I created the pull request and created a PyPI account (dr-geeno).

**Comment by ltalirz** [comment]
Thanks @dr-geeno , merged your PR and added you to PyPI project

**Comment by ltalirz** [comment]
Feel free to make the first PyPI release manually if you like - otherwise adding the github action pipeline is quite straightforward as well and easy to maintain 
After merging the workflow, you create a PyPI token, add it to the repo secrets, and then just push a tag to the repository.

I'm also adding you as a contributor to the Github repo

Edit: I am realizing that I don't have the rights to do that. I'll ask Torbjörn. In the meanwhile, feel free to upload v2.1.0 to PyPI

**Comment by dr-geeno** [comment]
Thanks for the help @ltalirz . I did another pull request, I added a cif file for testing the bug that was corrected. I will update on PyPI after merge and then will look into creating the automatic update anytime the version is changed. Do you also use TestPyPI? In case, could you add me also there as contributor? Name account is the same: dr-geeno.

**Comment by ltalirz** [comment]
Cheers, invite sent for test pypi
